version: '3.8'

services:
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_api
    command: sh -c "python manage.py runserver 0.0.0.0:8003"
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    
    


networks:
  default:
    external:
      name: qualcommnetwork